### ISSUE TITLE
关于博客排序

### ISSUE THREAD

**Issue by Yenjeanhung** [yelog/hexo-theme-3-hexo#1]
希望能增加博客按时间降序排列

**Comment by yelog** [comment]
blog排序可以参考这篇文章 [Hexo置顶及排序问题](http://yelog.org/2017/02/24/tools/Hexo%E7%BD%AE%E9%A1%B6%E5%8F%8A%E6%8E%92%E5%BA%8F%E9%97%AE%E9%A2%98%E5%A4%84%E7%90%86/)，希望可以帮到你

**Comment by yelog** [comment]
@Yenjeanhung 如果问题解决的话，可以把issue关掉
