### ISSUE TITLE
公式有引用的时候，需要刷新一下才能显示公式

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#10]
例如以下测试原文：

```
$$
f_{test} = \int a_b \cdot dt 
{\tag {1-1}} {\label {1-1}}
$$

引用公式 $\eqref {1-1}$
```

加了 "label" 后，公式就不能渲染出来，需要刷新一下才行。
一般第一次点击 第二段标题栏 的文章，公式可以正确渲染，但第二次点击，带 "label“ 的公式就不能渲染出来的，这个问题有解吗？

**Comment by yelog** [comment]
确实存在这个问题，看了官方 [wiki](https://github.com/mathjax/MathJax-docs/wiki/Labelled-equations-are-not-rendered-when-re-typeset)，是因为 `MathJax.Hub.Typeset()` 这个方法没有重置 `label` 造成 label 值重复而渲染失败，已经修复了，拉取最新的代码即可。

**Comment by yehuohan** [comment]
好的！！
