### ISSUE TITLE
网页代码块中的大括号变成html实体了

### ISSUE THREAD

**Issue by yionr** [yelog/hexo-theme-3-hexo#100]
看到博主的博客中显示也这样我就放心了，还以为是自己哪里乱配配置错了，嘿嘿
![image](https://user-images.githubusercontent.com/30925732/92127587-0bafc480-ee34-11ea-8076-1c946f27ce1e.png)

**Comment by Yionr** [comment]
![image](https://user-images.githubusercontent.com/30925732/92701764-f7fbe500-f382-11ea-92a1-5c427928819b.png)
初步发现 问题是因为`&`这个符号被什么东西自动转换成对应的实体`&amp;`才导致网页无法正确将`&#123`解析为`{`,因为实际上解析的是`&amp;#123`。
可惜自己学习进度太缓慢了，前端还没开始学框架，不然这是我最接近有能力提交一个PR的机会！加油

**Comment by chinobing** [comment]
是hexo5.0之后才出现的问题， 估计是hexo本身的转义问题。 我之前用3-hexo的theme也有这个问题，今天特意修复了并写下了过程，你可以试试：https://coding.f10.org/HEXO/%E4%BF%AE%E5%A4%8Dhexo%E8%8A%B1%E6%8B%AC%E5%8F%B7%E6%98%BE%E7%A4%BA%E4%B8%BA%E5%AD%97%E7%AC%A6%E4%B8%B2123%E5%92%8C125/

**Comment by Yionr** [comment]
好像是解决了，十分感谢！
不过根据你的博客操作还是遇到了一点小问题，贴一下
首先是，我的highlight.js/lib下没有core.js文件 。
![image](https://user-images.githubusercontent.com/30925732/101611334-5862f700-3a44-11eb-9e45-14a796fafdf6.png)
不过和你的文件对比了一下，我发现我的highlight.js特别大，然后进去找，发现这里面有escape方法和你贴的挺像的，我修改的是他。
然后根目录的_config.yml文件中，我原本并没有prismjs相关字段，加上去之后执行hexo命令会报错。我就没加，之后启动发现问题解决

**Comment by chinobing** [comment]
prismjs是5.0之后才有的，估计是hexo版本不一样的原因. 解决了就好

**Comment by qinfinger** [comment]
为什么你们的对话传到了我的邮箱里？这是什么机制

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
