### ISSUE TITLE
目录显示不全

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#11]
如果Markdown目录过高，就会显示不全。
我在3-hexo\source\css\_partial\full-toc.styl将post-toc的高度改82%，可以显示全了，目录下拉条也有[上下箭头](http://yhhx.tech/2017/06/07/%E7%AC%94%E8%AE%B0/%E6%88%91%E7%9A%84%E8%AE%BE%E7%BD%AE-in-Ubuntu/)了。

```
  .post-toc
    width 200px
    height 82%
```

**Comment by yelog** [comment]
嗯，这个是由于 .post-toc 的高度过大引起的，去掉 .post-toc 的 height 声明即可，代码已经提交

**Comment by yehuohan** [comment]
好的
