### ISSUE TITLE
nproess与videojs冲突

### ISSUE THREAD

**Issue by pharaohnie** [yelog/hexo-theme-3-hexo#113]
hello，有个关于3-hexo主题的问题求教。我在每篇post中使用了videojs，经过测试，如果开启了nproess.js，就会有很大几率无法打开视频。关了nproess.js就能解决。但如果关闭nproess.js后，在分类1中点完了一篇文章，就会自动跳回到所有问题。

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
