### ISSUE TITLE
代码块的高级功能无法使用问题

### ISSUE THREAD

**Issue by Elinpf** [yelog/hexo-theme-3-hexo#114]
hi， 我在hexo的官方文档看到代码块有支持高级功能，如下：

![image](https://user-images.githubusercontent.com/18662258/124845407-43921600-dfc9-11eb-8164-4a82a747627e.png)

但是却无法使用，应该做如何调整？

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
