### ISSUE TITLE
谢谢分享

### ISSUE THREAD

**Issue by wujita01** [yelog/hexo-theme-3-hexo#117]
谢谢您的分享，优点就不说了。很喜欢三段式的方式。希望能增加主题的质感，现在的配色感觉有点LOW。哈哈

**Comment by JIeJaitt** [comment]
有点像语雀，很好用。但是我也觉得配色稍微有点low ，hhh～～

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
