### ISSUE TITLE
你的博客 现在点击分类 好像没反应

### ISSUE THREAD

**Issue by rankaiyx** [yelog/hexo-theme-3-hexo#119]
如题

**Comment by rankaiyx** [comment]
可能是你之前说的这个原因
[yelog](https://github.com/yelog) commented [on 22 Mar 2019](https://github.com/yelog/hexo-theme-3-hexo/issues/26#issuecomment-475497564)
bootcdn 出问题了，导致jquery没有加载下来，改用其他的吧。
修改 _config.yml 中的 cdn->jquery 如下

jquery: //code.jquery.com/jquery-3.3.1.min.js

**Comment by rankaiyx** [comment]
又崩了

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
