### ISSUE TITLE
点击发邮件图标没反应

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#12]
点击邮件图标后没有反应，没有弹出发送邮件的页面。

**Comment by yelog** [comment]
。。。现在还会有问题吗，当时出现问题的设备是什么？

**Comment by yehuohan** [comment]
目前使用的是最新版，点击邮件图标后，还是没有弹出发送邮件的页面。

系统：windows8.1 chrome 62.0.3202.89

我点击你博客的邮件图标也没反应，你点击自己博客邮件图标有反应吗？

**Comment by yelog** [comment]
那应该是你的系统中没有邮件应用（如微软自带的、邮箱大师等），导致mailto不起作用

**Comment by yehuohan** [comment]
那就是了，我电脑中没装，我看到其它主题是弹出网页邮件发送界面，误以为都是这样的~~
