### ISSUE TITLE
Bug 分类如果是纯数字 点击该分类 会报错 并且分类筛选无效

### ISSUE THREAD

**Issue by rankaiyx** [yelog/hexo-theme-3-hexo#120]
报错信息
Uncaught TypeError: $(...).data(...).split is not script.js?v=1.1.0 a function 

测试时发现的问题  正常使用应该不会出现纯数字分类 因此也可以不必修复 只需在说明里注明 不可使用纯数字做分类

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
