### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by mao-design** [yelog/hexo-theme-3-hexo#125]
博客上的图片有几率会出现点击图片，图片会变小的情况，按理说因该是变大的；有次我在博主的博客上查找博客的使用资料时，发现博主的博客也会有这种情况，但是这种情况并不频繁，只是有几率触发，必须刷新一下页面才能恢复正常，也不知道是不是我的原因，我使用的是edge浏览器，这会不会和网速有关，我的网有时候会有点差。

**Comment by mao-design** [comment]
但是博主的博客真的好好看，即简约，而且文章的分类也一目了然，真的爱了😍

**Comment by yelog** [comment]
暂时没有复现, 先进行关闭, 如果仍然遇到, 可以再次打开讨论.
