### ISSUE TITLE
md语法

### ISSUE THREAD

**Issue by oy689264** [yelog/hexo-theme-3-hexo#127]
![image](https://user-images.githubusercontent.com/59795778/206212882-e2e64440-6216-439c-b597-eb4cdfdba220.png)
你好，我看到你的代码块是可以复制的，我使用同样的md 语法显示的却是
![image](https://user-images.githubusercontent.com/59795778/206213036-18499331-d8eb-46d7-9b63-01a8a7d4929b.png)
这个样子的是有哪里需要设置的吗

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
