### ISSUE TITLE
默认显示大纲以及调整大纲宽度

### ISSUE THREAD

**Issue by rosingle** [yelog/hexo-theme-3-hexo#13]
如题
不知为何好几次进入自己的网站都需要点一下那个目录大纲才会出来，可否设置为默认就有？

还有就是大纲宽度太窄有时候不合适，不知道能不能提供改宽度的设置

**Comment by yelog** [comment]
手机端由于要显示内容，默认隐藏文章目录

目录宽度这个可以有，这几天添加一下宽度配置，请留意更新

[3-hexo开发日志-持续更新](http://yelog.org/2017/03/13/3-hexo-logs/)
