### ISSUE TITLE
怎么根据categories 排序

### ISSUE THREAD

**Issue by TrinityLeaves** [yelog/hexo-theme-3-hexo#135]
我现在需要根据categories 排序。但是在代码里面只有根据top和date的排序，直接.categories 也排序不了，我想要文章的顺序能够跟左边目录的一样，应该怎么做？

**Comment by yelog** [comment]
可以查看文档: https://yelog.org/2017/03/23/3-hexo-instruction/#4-1-%E5%88%86%E7%B1%BB%E6%8E%92%E5%BA%8F

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
