### ISSUE TITLE
关于图片显示方式问题

### ISSUE THREAD

**Issue by rosemengzi** [yelog/hexo-theme-3-hexo#136]
您好，我想让文字和图片显示在同一行，但主题设置会让图片会独占一行，请问有什么解决方案吗，例如

这是一张图片![生气](https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon6.png)

![image](https://github.com/yelog/hexo-theme-3-hexo/assets/59559434/17e8beb8-dfa5-42ea-b6ed-2edd9bb328bd)

求解，先感谢抽空解答了

**Comment by yelog** [comment]
行内显示图片得控制图片大小, 建议使用 img 标签控制显示, 如下
```html
这是一张图片<img src="https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon6.png" alt="生气" style="width:20px; height:20px; vertical-align: middle;" data-ignore>
```

**Comment by rosemengzi** [comment]
太感谢解答了，其实有试过用img标签显示，不过我模仿了渲染后的样式，导致PC端显示是正常的但到移动端就显示有问题了，字会顶格显示，如下
<div class='div_img' style='text-align:left'&gt;
你好，<br/&gt;
这是一张图片
<img src="https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon6.png" alt="生气"&gt;
</div&gt;




移动端显示：

顶出来了，没有前间隔了，一时间又想不到更好的方案就来求助大佬了，总之多谢百忙之中抽空解答！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yelog/hexo-theme-3-hexo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yelog/hexo-theme-3-hexo] 关于图片显示方式问题 (Issue #136)





 
行内显示图片得控制图片大小, 建议使用 img 标签控制显示, 如下
 这是一张图片<img src="https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/editor/images/client/image_emoticon6.png" alt="生气" style="width:20px; height:20px; vertical-align: middle;" data-ignore&gt;

**Comment by yelog** [comment]
对了, 重点是需要在 img 标签内写了 data-ignore 属性, 这样主题就不会对这个img标签做处理

**Comment by rosemengzi** [comment]
可以，你这条信息很关键，多谢大佬抽空解答
