### ISSUE TITLE
直接显示打赏二维码 + 取消Index页面

### ISSUE THREAD

**Issue by rosingle** [yelog/hexo-theme-3-hexo#14]
谢谢你这个主题，是我一直想要追求的效果~ 

1 我想问一下能不能直接显示打赏二维码，因为估计没人会去打开那个页面

2 可否提供一个选项取消index页面，就是那个★是★的博客的，首先这个对读者没什么用，另外手机端按头像时老是会回到那个页面而不是干净的主页去啊，有点没有必要

**Comment by yelog** [comment]
关于二维码的提议非常好，随后会提供默认显示和隐藏的设置，请请留意更新。

关于首页，是提供 /layout/indexs.md 页面做一下介绍，可以完全当一篇文章写。

不知你想要的首页效果是什么样子的，可以详细说一下，交流一下

**Comment by rosingle** [comment]
谢谢回复！

其实主要是我的博客文章都特别长，我的习惯是把所有类似的内容都放一个页面，所以我才特别喜欢提纲这个功能，所以才想到透明化。

这几天自己捣鼓了一下，因为不懂html和css所以都是瞎蒙的，http://rosingle.github.io
这是现在的效果
这是我的长文章http://rosingle.github.io/2017/10/23/hello_world/

我想要达到的效果是
1 手机端现在这样已经差不多了，不过我想要他直接就把tag全显示出来而不用去看那个键，然后就是进入文章直接就出来提纲可以选想看的部分，提纲能够有点透明度
2 电脑端我觉挺好的因为屏幕大所以可以多弄点内容，就是想可以把文章列表的宽度搞窄一点

不过我理解不是每个人都有这样的需求，请你指点下以下几个效果在代码哪里大概怎么实现，我自己去查查一些细节

★★手机端电脑端进文章时提纲，tag都自动出现
★★提纲透明度调节
★电脑端文章列表宽度调节（不是特别重要）

谢谢！

**Comment by rosingle** [comment]
更新~

其实主要是我的博客文章都特别长，我的习惯是把所有类似的内容都放一个页面，所以我才特别喜欢提纲这个功能，所以才想到透明化。 

这几天自己捣鼓了一下，因为不懂html和css所以都是瞎蒙的，http://rosingle.github.io 这是现在的效果 这是我的长文章http://rosingle.github.io/2017/10/23/hello_world/ 

我想要达到的效果是 
1 手机端现在这样已经差不多了，不过我想要他直接就把tag全显示出来而不用去看那个键，然后就是进入文章直接就出来提纲可以选想看的部分，提纲能够有点透明度 
2 电脑端我觉挺好的因为屏幕大所以可以多弄点内容，就是想可以把文章列表的宽度搞窄一点，还有进入全屏文章模式时页面两边的留白能够小一点或者基本没有 不过我理解不是每个人都有这样的需求，请你指点下以下几个效果在代码哪里大概怎么实现，我自己去查查一些细节 

总结
★★手机端电脑端进文章时**提纲，tag**都自动出现 
★★提纲透明度调节 
★★提纲透明度调节 
★★★★电脑端文章列表宽度调节和文章视图时两边留白消除

**Comment by yelog** [comment]
*关于提纲：*
如果手机端默认显示提纲（如果你的意思是指文章列表页），会遮挡内容。比如说你要分享你的这篇文章
 http://rosingle.github.io/2017/10/23/hello_world/  ，那一定是希望访问者首先看到的是文章内容，因为这才是你分享链接的重点，而不是让用户第一眼看文章列表。

*关于提纲透明度*
如果调整了提纲透明度，则会与文章内容混在一起，会很难看

以上只是我的观点，下面提供一下你的需求的解决办法：
## 一、手机端默认展示 提纲
1. 删掉 `source/css/mobile.styl` 的 39-41行，如下三行
```css
   margin-left -492px
   &.fullscreen
      margin-left 0px
```
2. 修改 `layout/index.ejs` 的第5行，改为如下所示：
```html
<aside class="nav">
```
## 二、默认显示 tag
1. 修改 `source/js/script.js` 的 315 行 加入如下代码
```js
$("#tagswitch").trigger('click');
```
## 三、提纲透明度调节
修改 `scource/css/style.styl` 的 33 行 处，加一行 `opacity 0.8` ，上下文如下
```css
.nav
  opacity 0.8
  width 542px
```
值得范围可为` 0~1 `，依次从全透明~不透明
