### ISSUE TITLE
更换CDN加速

### ISSUE THREAD

**Issue by wings1848** [yelog/hexo-theme-3-hexo#142]
主题所使用的CDN加速似乎有点问题了?

**Comment by yelog** [comment]
<img width="1243" alt="image" src="https://github.com/yelog/hexo-theme-3-hexo/assets/14227866/a4c9020c-3dc5-4ce0-a297-359e08eb5da0">
cdn.jsdelivr.net 在大陆的访问确实有问题

**Comment by ewintec** [comment]
CDN:
  jquery: //cdn.bytedance.com/cdn/expire-1-M/jquery/3.5.1/jquery.min.js
  jquery_cookie: //cdn.bytedance.com/cdn/expire-1-M/jquery-cookie/1.4.1/jquery.cookie.min.js
#  highlight: //unpkg.com/npm/highlightjs@9.16.2/highlight.pack.min.js
  highlight: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.16.2/highlight.min.js
  pjax: //cdnjs.cloudflare.com/ajax/libs/jquery.pjax/2.0.1/jquery.pjax.min.js
  animate: //cdn.bytedance.com/cdn/expire-1-M/animate.css/4.1.0/animate.min.css
  nprogres_js: //cdn.bytecdntp.com/cdn/expire-1-M/nprogress/0.2.0/nprogress.min.js
  mathjax: //cdn.bytecdntp.com/cdn/expire-1-M/mathjax/2.7.9/config/TeX-MML-AM_CHTML.min.js
  photoswipe_js: //cdn.bytedance.com/cdn/expire-1-M/photoswipe/4.1.3/photoswipe.min.js
  photoswipe_ui_js: //cdn.bytedance.com/cdn/expire-1-M/photoswipe/4.1.3/photoswipe-ui-default.min.js
  photoswipe_css: //cdn.bytedance.com/cdn/expire-1-M/photoswipe/4.1.3/photoswipe.min.css
  photoswipe_skin_css: //cdn.bytedance.com/cdn/expire-1-M/photoswipe/4.1.3/default-skin/default-skin.min.css
##############################

注意：mathjax/2.7.9 有报存MathJax拒绝服务漏洞：https://wlfw.zepc.edu.cn/info/1712/64262.htm
