### ISSUE TITLE
为什么我使能3-hexo后文章显示很丑

### ISSUE THREAD

**Issue by wenfei6316** [yelog/hexo-theme-3-hexo#143]
博主你好，我使用了3-hexo后文章是这样的
![image](https://github.com/yelog/hexo-theme-3-hexo/assets/42144440/20008189-d4c9-4f87-b7a1-c7825359e91f)
代码没有了高亮的说法了

**Comment by yelog** [comment]
按照说明中的 1.2, 把 hexo 的高亮关了试试, https://yelog.org/2017/03/23/3-hexo-instruction
