### ISSUE TITLE
首页的内容可以自己修改么？why blog可以修改其他内容么？

### ISSUE THREAD

**Issue by Alex200411** [yelog/hexo-theme-3-hexo#147]
![屏幕截图 2024-08-29 161858](https://github.com/user-attachments/assets/d5d9e3dc-c823-4c66-85df-85051d8b6a8d)
这里的why blog可以自行修改么，没有找到修改的地方。感谢！

**Comment by yelog** [comment]
可以参考这里 [3-hexo配置首页](https://yelog.org/2017/03/13/3-hexo-homepage/)
