### ISSUE TITLE
默认显示tab + 取消或修改友情链接 + 文章列表宽度控制

### ISSUE THREAD

**Issue by rosingle** [yelog/hexo-theme-3-hexo#15]
好像submit太多了，不知道作者会不会看

1 我觉得如果能设置默认显示tab会好很多因为有的人不知道有这东西

2 另外就是友链那个箭头不是很直观，尤其是手机界面，我很多朋友都没搞懂怎么回到文章页，可能把箭头方向改成朝左更好理解，最好要是能清楚的写回到文章列表就好了。

3 文章列表宽度如果可控应该也会更好，手机上空间太小

4 目录能不能实现一定程度的透明呢

5 最后一个可能有点难，能不能实现文章内容搜索呢？ 如果这样的话就完美啦

**Comment by yelog** [comment]
不好意思，这几天都在搬家，所以没有抽空来看。

看了你的问题，一一回答一下
1.  pc端是默认显示文章列表的，手机端默认不展示文章列表，因为考虑到通过链接进来读者首先是奔着内容去的，所以以内容为主，在手机端默认不展示文章列表

2. 友链的那个返回箭头确实不明显，这个交互效果需要改进

3. 文章列表在手机端显示的宽度为100%，不知说的是哪种情况，如果能有截图，就再好不过了。

4. 目录透明度，这个有点众口难调，可根据个人喜好，自己调整一下即可

5. 这个搜索，很早就想做了，当时研究了几种解决策略，都不能很好的融进主题内，后来就一直拖，啊哈，这几天在研究下
