### ISSUE TITLE
文章目录异常

### ISSUE THREAD

**Issue by faust427** [yelog/hexo-theme-3-hexo#16]
大佬我使用了您的主题发现文章右侧的节点目录有点问题,
`<li class="toc-item toc-level-4">
<a class="toc-link" href="#代码内配置">
<span class="toc-text">
</span>
</a>
<a href="#代码内配置" class="headerlink" title="代码内配置">
</a>
代码内配置</li>`
生成的文章节点文本没有被a标签包裹都在a标签外面导致a标签不能点击跳转,但是看您的博客上是没有这个问题的,是我配置得有问题吗...

**Comment by yelog** [comment]
我这边测试了没有问题，可否把有问题的页面链接发一下，我看一下

**Comment by yelog** [comment]
今天帮其他人解决问题也发现了这个问题，是 hexo 3.4.3 的一个bug，升级一下 hexo，即可。
issue： https://github.com/hexojs/hexo/issues/2896
