### ISSUE TITLE
代码框显示效果异常

### ISSUE THREAD

**Issue by CuriousFu** [yelog/hexo-theme-3-hexo#18]
参考了阁下的主题，很棒，但是文章的代码显示有点问题，如图下所示：
![](https://s1.ax1x.com/2018/01/31/9CoPd1.png)

**Comment by yelog** [comment]
需要关闭hexo自带的高亮，具体可到下面链接中查看。
http://yelog.org/2017/03/23/3-hexo-instruction/#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE

**Comment by CuriousFu** [comment]
谢啦，解决了
