### ISSUE TITLE
markdown矩阵显示问题

### ISSUE THREAD

**Issue by CuriousFu** [yelog/hexo-theme-3-hexo#19]
![](https://s1.ax1x.com/2018/02/02/9EtHnU.png)

**Comment by yelog** [comment]
实在不好意思，年末赶进度，没有及时回复。。。。。。。

这个问题是由于 hexo渲染器 和 mathjax 的语法冲突。

可参考这篇文章的第一点，来解决这个问题：http://yelog.org/2017/07/05/3-hexo-mathjax/

**Comment by CuriousFu** [comment]
谢谢👍😊
