### ISSUE TITLE
关于文章排序问题

### ISSUE THREAD

**Issue by Qifcn** [yelog/hexo-theme-3-hexo#20]
没有按照以时间，以前的文章在后新的文章在前的顺序
![tim 20180207234416](https://user-images.githubusercontent.com/34029055/35925711-66fafbdc-0c61-11e8-9426-fe59d82ffd12.png)

**Comment by Qifcn** [comment]
抱歉，没仔细看文档

**Comment by Qifcn** [comment]
http://yelog.org/2017/02/24/hexo-top-sort/

**Comment by yelog** [comment]
嗯
