### ISSUE TITLE
请问能否将_post目录下的第一级文件夹名称作为文章分类

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#21]
如题，想要将_post目录下的文件夹名称，作为文章文类，这样，设置或修改文章分类就方便多了，不用每次都更改categories属性。
请问有可能实现吗？

**Comment by yelog** [comment]
不好意思，这么长时间才回复。

提到的功能， hexo 没有提供这样的 api ，所以暂时无法实现。

**Comment by yehuohan** [comment]
哦哦，这样啊~~~
