### ISSUE TITLE
全文检索功能配置问题

### ISSUE THREAD

**Issue by Using1174** [yelog/hexo-theme-3-hexo#22]
看配置是需要一个search.xml文件支持，请问我要怎么生成这个search.xml文件呢？
我按照说明将
```
search:
  path: search.xml
  field: post
```

添加到根目录下的.config.yml里面了，但是启动之后还是无法执行全文搜索。

**Comment by yelog** [comment]
插件 hexo-generator-search 安装成功了吗？
>在 hexo 根目录 执行 npm install hexo-generator-search --save 安装插件

**Comment by Using1174** [comment]
解决了，感谢！
```
npm install hexo-generator-search –save
npm install hexo-generator-searchdb --save
```
这两个都需要安装，只安装第一个不能全文搜索。

**Comment by yelog** [comment]
不用啊，只需要安装第一个。
下面是我所有的依赖

![image](https://user-images.githubusercontent.com/14227866/38607280-c31960aa-3daa-11e8-9319-9a2044f5c4be.png)

**Comment by Using1174** [comment]
看了一下，我的现在只有第二个，请问这两个有什么区别吗？

**Comment by Using1174** [comment]
好的，感谢！我还是安装第一个吧。
