### ISSUE TITLE
关于配置和更换首页的问题

### ISSUE THREAD

**Issue by zhupengfeivip** [yelog/hexo-theme-3-hexo#25]
在使用这个主题时，一般都要有自己的配置和indexs.md主页，现在只能在主题下更改你的文件吗？
有没有办法在外面创建一个配置文件和index.md文件，可以替换你里面的？
你的主题在themes文件夹中，里面的git是指向你的github的，直接修改不是太合适吧？有没有办法解决呢？

**Comment by cocos56** [comment]
老哥，这个Index不支持使用@[TOC]自动生成目录

![image](https://user-images.githubusercontent.com/36597804/73646254-0333b780-46b4-11ea-86bb-4308eb9d72cb.png)

**Comment by cocos56** [comment]
博客首页的那个Index.md
