### ISSUE TITLE
目录，分类，tags等按钮不起作用？

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#26]
目录，分类，tags等按钮不起作用，我打你的博客也是这样？是我浏览器问题还是主题问题？或者是hexo的Bug?

**Comment by durongpeng** [comment]
我用的谷歌的浏览器没问题呀，主题我也是下载的别人的，并不是我写的


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：lurixing <notifications@github.com>
日期：2019-03-22 12:36:14
收件人：yelog/hexo-theme-3-hexo <hexo-theme-3-hexo@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[yelog/hexo-theme-3-hexo] 目录，分类，tags等按钮不起作用？ (#26)
目录，分类，tags等按钮不起作用，我打你的博客也是这样？是我浏览器问题还是主题问题？或者是hexo的Bug?

**Comment by yelog** [comment]
bootcdn 出问题了，导致jquery没有加载下来，改用其他的吧。
修改 _config.yml 中的 cdn->jquery 如下
```yml
jquery: //code.jquery.com/jquery-3.3.1.min.js
```
