### ISSUE TITLE
博客头像

### ISSUE THREAD

**Issue by gitrootid** [yelog/hexo-theme-3-hexo#28]

**Comment by gitrootid** [comment]
博客头像处的超链接，好像是只读取域名部份？ 不会跟着url，但是我的博客需要访问https://gitrootid.github.io/note/才有效，如果只是https://gitrootid.github.io会拿不到文件，返回404

**Comment by yelog** [comment]
嗯，疏忽了，已修复更新

**Comment by gitrootid** [comment]
测试已经正常，多谢！
