### ISSUE TITLE
背景

### ISSUE THREAD

**Issue by FunkyGod** [yelog/hexo-theme-3-hexo#29]
楼主，怎么给博客的首页添加背景图片呢？

**Comment by FunkyGod** [comment]
怎么设置多级目录呢，能举个例子吗？
categories:
-

**Comment by yelog** [comment]
暂时不支持多级目录，今天扩展一下，顺便把首页、文章页的背景图参数暴漏一下。

这两天可以关注一下更新日志：[3-hexo开发日志-持续更新](https://yelog.org/2017/03/13/3-hexo-logs/) 
3-hexo主题的使用(包括代码高亮等)可以参考 [3-hexo使用说明](https://yelog.org/2017/03/23/3-hexo-instruction/)

**Comment by yelog** [comment]
@FunkyGod 更新最新的主题，可以设置多级目录
在 `_config.xml` 中开启 `sub: true` 即可开启
```yml
category
    sub: true
```

文章中多个分类如下
```markdown
categories:
- 工具
- hexo
```
则会被解析为一层目录“工具”，二层目录“hexo”，效果如图所示
![image](https://user-images.githubusercontent.com/14227866/58078874-54f9e780-7be2-11e9-99f9-8feda17809f9.png)

**Comment by yelog** [comment]
@FunkyGod 背景图的设置也已经支持。
① `_config.xml` 配置默认背景图片

首页背景图： `index_bg_img: xxx.jpg`

文章页面背景图：`other_bg_img: xxx.jpg`

② 我们还可以单独给某篇文章设置背景图（优先级最高）
```markdown
title: 3-hexo开发日志-持续更新
bgImg: xxx.jpg  #设置这篇文章的背景图
```
