### ISSUE TITLE
火狐浏览器标签错位

### ISSUE THREAD

**Issue by Yenjeanhung** [yelog/hexo-theme-3-hexo#3]
用火狐浏览器打开博客时，标签会发生错位

**Comment by yelog** [comment]
是文章列表上方的标签，还是文章标题下方的标签，可以把出现错位的链接发一下吗

**Comment by Yenjeanhung** [comment]
![qq 20170318103438](https://cloud.githubusercontent.com/assets/13391658/24068305/74d6c5ac-0bc6-11e7-9b42-7709bf37780a.png)
是文章标题列表错位。我截了一张图，你看一下

**Comment by yelog** [comment]
确实存在这个bug，已经解决了

原因：由于fixfox不支持自定义滚动条，在某些版本的firefox中的滚动条宽度过大，导致宽度读取有误，从而导致文章错位。

解决方案：文章列表宽度已经调整为自适应，不会再出现由于各种情况导致的宽度适应问题。

再次访问试一下

**Comment by Yenjeanhung** [comment]
火狐还是有错位的情况，你用的版本是多少呢？我用的火狐是52.0.1 (32 位)
![qq 20170318172320](https://cloud.githubusercontent.com/assets/13391658/24070870/3cd0b200-0c00-11e7-95aa-3f41f7827c0f.png)

**Comment by yelog** [comment]
@Yenjeanhung 已经处理好了，应该不会再有问题了，你在试一下

**Comment by Yenjeanhung** [comment]
![qq 20170319195214](https://cloud.githubusercontent.com/assets/13391658/24080584/84f139a0-0cdd-11e7-9730-8b19e5d2182c.png)
这次可以了，火狐也可以正常使用了。
