### ISSUE TITLE
有几个显示的问题希望优化

### ISSUE THREAD

**Issue by wuqiyin** [yelog/hexo-theme-3-hexo#30]
1、代码多于100行的时候，行号的显示的问题
![image](https://user-images.githubusercontent.com/26370779/58743065-7027eb00-845d-11e9-82a6-fd09759c31a7.png)
2、tag开关wei位置偏移的问题
![image](https://user-images.githubusercontent.com/26370779/58743077-9fd6f300-845d-11e9-96ac-eaba0670e279.png)

**Comment by yelog** [comment]
已修复
