### ISSUE TITLE
CDN失效

### ISSUE THREAD

**Issue by zdaiot** [yelog/hexo-theme-3-hexo#33]
您好，看了您的主题感觉特别喜欢。但是我实际用的时候，按照`_config.yml`中的CDN设置，jquery和mathjax的CDN经常加载不进来，经常需要刷新好几遍才能加载进来，而且有的时候，加载进来了也是一闪而过。我看您的网站，CDN挺正常的，请问可以分享下么？

**Comment by yelog** [comment]
https://www.bootcdn.cn/jquery/

**Comment by zdaiot** [comment]
您好，我换了好几个mathpix的CDN，例如`mathjax: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML`或者`mathjax: //cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML`都不行

提示说：
```
Error: Can't make callback from given data MathJax.js:19:5527
    USING https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js:19
    Push https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js:19
    Queue https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js:19
    afterPjax http://localhost:4000/js/script.js?v=1.0.1:62
    jQuery 6
```
请问您有什么建议么？

**Comment by yelog** [comment]
不应该啊，你访问 [https://yelog.org/2017/07/05/3-hexo-mathjax/ ](https://yelog.org/2017/07/05/3-hexo-mathjax/ ) 会有问题吗

**Comment by zdaiot** [comment]
您好，没有问题。是不是因为我是在本地`hexo s`测试的，还没部署到github上
