### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by ethanvc** [yelog/hexo-theme-3-hexo#40]
发现有2个问题：
1. 代码区域显示异常。
2. 目录无法跳转。
https://ethanvc.github.io/2019/09/13/GDB%E5%91%BD%E4%BB%A4%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/#null

**Comment by yelog** [comment]
代码块的问题需要关掉hexo自己的代码高亮。在博客根目录的 `_config.yml` 中
```yml
highlight:
  enable: false
```
一些基本设置都可以在 [3-hexo使用说明](https://yelog.org/2017/03/23/3-hexo-instruction/) 找到

目录无法跳转的问题，没有复现

**Comment by ethanvc** [comment]
![image](https://user-images.githubusercontent.com/11705708/64931033-4f4aa080-d868-11e9-8aa1-398236853b4d.png)
应该是生成目录的时候，tag不见了，看左下角的URl。

**Comment by yelog** [comment]
不应该，你的 `hexo` 版本多少

**Comment by ethanvc** [comment]
目录无法跳转的问题解决了。问题原因是，生成的下面的代码有问题：
 <div class="toc-ref">
    
        <ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#null"><span clas
注意href="#null"
解决方法是，卸载hexo-toc模块。（npm uninstall hexo-toc）
