### ISSUE TITLE
日期排序

### ISSUE THREAD

**Issue by 422926799** [yelog/hexo-theme-3-hexo#41]
能从最近的日期依次排序吗

**Comment by yelog** [comment]
可以查看这篇文章解决问题 [Hexo置顶及排序问题](https://yelog.org/2017/02/24/hexo-top-sort/)

**Comment by 422926799** [comment]
> 可以查看这篇文章解决问题[HEXO置顶及排序问题](https://yelog.org/2017/02/24/hexo-top-sort/)

谢了
