### ISSUE TITLE
能添加使用[toc]代码就自动生成目录吗？

### ISSUE THREAD

**Issue by cocos56** [yelog/hexo-theme-3-hexo#43]
效果可以参考：https://blog.csdn.net/COCO56/article/details/99176024

**Comment by yelog** [comment]
更新最新的主题，包含如下两个文件，效果及关键字 [3-hexo文章内toc生成](https://yelog.org/2019/09/24/3-hexo-toc/)
![image](https://user-images.githubusercontent.com/14227866/65476162-982bd600-deb4-11e9-8345-023aa39f2ca3.png)

**Comment by COCO5666** [comment]
谢谢，原来是关键字用错了

**Comment by yelog** [comment]
不是，这个功能今天早上刚加的

**Comment by COCO5666** [comment]
嗯嗯，非常感谢，那我先升级下再用

**Comment by cocos56** [comment]
老哥，这个能不能自定义改成使用`@[TOC]`或者`[TOC]`？我用VS Code本地排版时使用`[TOC]`才会显示目录

**Comment by yelog** [comment]
可以使用 `@[TOC]` ，这个不区分大小写

**Comment by cocos56** [comment]
好，用VS Code本地排版时使用[TOC]才会显示目录，所以如果把截图自己根据需要选择使用@[TOC]或者[TOC]都可以的话就比较好了

**Comment by cocos56** [comment]
我修改相关源码，发现改了之后会报错
![image](https://user-images.githubusercontent.com/36597804/71820883-81a83400-30cb-11ea-8cb5-a124431ced81.png)

**Comment by cocos56** [comment]
刚才是我的正则表达式写错了，又弄了下，可以啦
![image](https://user-images.githubusercontent.com/36597804/71821193-6db10200-30cc-11ea-97a4-aab542792cd4.png)
