### ISSUE TITLE
左下角自定义菜单 menu  '关于' 按钮 出现异常

### ISSUE THREAD

**Issue by cocos56** [yelog/hexo-theme-3-hexo#46]
# 左下角自定义菜单
menu:
  about:  # '关于' 按钮
    on: true # 是否显示
    url: https://coco56.gitee.io/blog/about/  # 跳转链接
    type: 3 # 跳转类型 1：站内异步跳转 2：当前页面跳转 3：打开新的tab页
  friend: # '友链' 按钮

**Comment by COCO5666** [comment]
这个地方不能论怎么改，都会转到https://coco5666.github.io/about

**Comment by COCO5666** [comment]
而由于我的博客在 https://coco56.gitee.io/blog，因此需要转到 https://coco56.gitee.io/blog/about/

**Comment by cocos56** [comment]
我通过修改源代码解决了这一问题
![image](https://user-images.githubusercontent.com/36597804/71782880-279b6600-301a-11ea-8fc8-550d25fceb98.png)
