### ISSUE TITLE
请问首页的博客是按照什么规则排序的?

### ISSUE THREAD

**Issue by shdvgj** [yelog/hexo-theme-3-hexo#47]
目前没看到规律, 如果有可以设置排序规则的地方, 也请告知一下

**Comment by yelog** [comment]
文章排序参考这篇文章：[Hexo置顶及排序问题](https://yelog.org/2017/02/24/hexo-top-sort/)

**Comment by hqweay** [comment]
环境：  "hexo": "^4.0.0", "hexo-generator-index": "^1.0.0",
按 @yelog 博文的操作不能实现按时间逆序归档，在 nav-right.ejs 里改为
```esj
 <% site.posts.sort("date", "desc").forEach(function(post, i){  %>
```
可以了。
