### ISSUE TITLE
代码高亮没显示效果

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#5]
我使用3-hexo后，代码高亮没效果
[这里](https://zhidao.baidu.com/question/565351697351195244.html)

**Comment by yelog** [comment]
要关闭hexo根目录下_config.yml中的高亮设置
highlight:
  enable: false

具体可查看这篇文章中关于代码高亮的设置
[3-hexo使用说明](http://yelog.org/2017/03/23/3-hexo-instruction/)

**Comment by yehuohan** [comment]
还是不行，
highlight:
  on: false # true开启代码高亮
on 和enable选项都试了

还是谢谢你~

**Comment by yelog** [comment]
3-hexo主题目录下的_config.yml中 设置 
highlight:
on: true
在你生成的hexo博客的根目录也有一个_config.yml，里面需要关闭高亮设置，如下
highlight:
enable: false

整个过程是关掉hexo默认的高亮样式，启用主题的高亮样式。

**Comment by yehuohan** [comment]
加了后hexo s出错： 

FATAL duplicated mapping key at line 86, column -171:
    highlight:
    ^
YAMLException: duplicated mapping key at line 86, column -171:
    highlight:

我hexo可能有什么插件没装吧

这么晚还回答，给满分！！

**Comment by yelog** [comment]
根据提示，应该是你新增了上面需要你改动的那两个参数，那两个参数在原文档中是存在的，只需修改即可。如果还有问题，可贴出两个配置文件内容，帮你看一下是什么问题。

**Comment by yehuohan** [comment]
我给你邮箱jaytp@qq.com发了异常信息和配置过来，你可以看下

**Comment by yelog** [comment]
根据你反馈的报错提示，应该是你在 hexo 根目录_config.yml中添加了下面配置造成的。
```yml
highlight:
  enable: false
```
而在 hexo根目录 的 _config.yml 中 ，原本就有下面这个配置。
```yml
highlight:
  enable: true
```
你只需找到这个配置，然后改为 `enable: false` 即可，如下
```yml
highlight:
  enable: false
```
