### ISSUE TITLE
点击标签全都是弹出一个新的tab窗口

### ISSUE THREAD

**Issue by FuzongQiu** [yelog/hexo-theme-3-hexo#52]
我的站点
https://fuzongqiu.github.io/

看了主题的配置好像没有相关的配置

**Comment by FuzongQiu** [comment]
例子：
1.点击tags里的选项
2.点击文章的
结果都是弹出一个新窗口 about:blank#blocked

**Comment by yelog** [comment]
你是不是有修改源码，或者装了什么相关插件，导致索引都加上了 target="_blank"
![image](https://user-images.githubusercontent.com/14227866/68103035-2f526780-ff10-11e9-8d0a-eb79ef91e0cb.png)

**Comment by FuzongQiu** [comment]
没装其他插件。
我刚才重新在本地 hexo init ,在clone了你的主题，发现还是这样。

**Comment by FuzongQiu** [comment]
插件的话，我记得就装了一个排序的，一个搜索的

**Comment by FuzongQiu** [comment]
npm install hexo-generator-index-pin-top --save
npm install hexo-generator-search --save

**Comment by FuzongQiu** [comment]
看了好像是所有的a标签都加上了 target="_blank" ，但具体原因不清楚。

**Comment by yelog** [comment]
hexo init 的目录下有一个 package.json 内容贴一下

**Comment by FuzongQiu** [comment]
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

**Comment by akbcd** [comment]
> 例子：
> 1.点击tags里的选项
> 2.点击文章的
> 结果都是弹出一个新窗口 about:blank#blocked

hexo4.0版本新增特性，在用hexo4.0生成网页时，.ejs文件中运用javascript:阻止跳转的a标签都加上了 target="_blank" 和rel="noopener属性"。
解决办法:不运用javascript:阻止a标签跳转，或者将hexo版本降为hexo3.几版本
也可以等待主题开发者适配

**Comment by akbcd** [comment]
> 例子：
> 1.点击tags里的选项
> 2.点击文章的
> 结果都是弹出一个新窗口 about:blank#blocked

hexo4.0自动生成的。用hexo4.0生成网页时，.ejs文件中阻止a标签的href为javascript时，hexo4.0自动添加上那两个属性。解决办法
将hexo版本降低(改为3.几版本)或者修改阻止a标签跳转的方式

**Comment by yelog** [comment]
这是 hexo4.0 造成的问题，已修复，更新主题即可

**Comment by FuzongQiu** [comment]
好的，已经ok。谢谢
