### ISSUE TITLE
部署之后为什么页面布局完全是乱的，像是布局文件没有起作用

### ISSUE THREAD

**Issue by BrightStonebody** [yelog/hexo-theme-3-hexo#53]

**Comment by XiongDi-Blog** [comment]
我也遇到这个问题
部署后成没有样式的状态：
![image](https://user-images.githubusercontent.com/59019047/71255699-9cf40f00-2369-11ea-836d-d9ffc17665e4.png)
请求似乎比localhost少了10个左右，加载样式时没有报错

**Comment by redtecher** [comment]
> 
> 
> 我也遇到这个问题
> 部署后成没有样式的状态：
> ![image](https://user-images.githubusercontent.com/59019047/71255699-9cf40f00-2369-11ea-836d-d9ffc17665e4.png)
> 请求似乎比localhost少了10个左右，加载样式时没有报错

请问您解决了吗，我这边也遇到了，一直没解决
