### ISSUE TITLE
gitalk 显示404，无法正确加载

### ISSUE THREAD

**Issue by dickens88** [yelog/hexo-theme-3-hexo#60]
大拿你好，我使用最新的3-hexo主题，配置了gitalk但是显示404错误，F12看到似乎参数没有正确传到github，如下图

![image](https://user-images.githubusercontent.com/8390209/71304565-9bb8f580-23ee-11ea-9696-0a46d7f03acd.png)

``3-hexo\_config.yml``配置如下：
```
gitalk:
  githubID:'dickens88'
  repo:'dearcharles'
  ClientID:'<git id>'
  ClientSecret:'<git secret>'
  adminUser:['dickens88']
  distractionFreeMode:true
  language:'en'
  perPage:10
```
能否帮忙看下具体哪里配置错误，谢谢？http://dearcharles.cn/

**Comment by kaisawind** [comment]
https://api.github.com/repos/kaisawind/kaisawind.github.io/issues
https://api.github.com/repos///issues

your username and repo is incorrect. maybe you should delete `'`.

```conf
gitalk:
  githubID: kaisawind
  repo: kaisawind.github.io
  ClientID: 
  ClientSecret: 
  adminUser: kaisawind
  distractionFreeMode: true
  language: zh-CN
  perPage: 10
```
