### ISSUE TITLE
MarkDown 代码块最后一行的行号显示问题

### ISSUE THREAD

**Issue by zhangyaaoo** [yelog/hexo-theme-3-hexo#64]
![image](https://user-images.githubusercontent.com/42711815/72220141-9a5f9080-3588-11ea-8553-109f51864041.png)

如上图，如果代码块的最后一行有一个空行存在，则行号显示正常。如果没有，则最后一行的行号显示不出来。

**Comment by kaisawind** [comment]
yes, there is something wrong with line number.

i just add `+1` when show line number.

https://github.com/kaisawind/hexo-theme-3-hexo/commit/bc836d354240f45ec7ae97d7492c0656de8b6c8e
```
         $(this).addClass('has-numbering ' + widther)
                    .parent()
                    .append($numbering);
            // for(var i=1;i<=lines;i++){
            for(var i=1;i<=lines+1;i++){
                $numbering.append($('<li/>').text(i));
            }
        });
```

**Comment by F-numen** [comment]
![image](https://user-images.githubusercontent.com/35397967/73458530-679f0000-43b0-11ea-924f-c5964379f10e.png)
lines计算有误，themes\3-hexo\layout\_partial\footer.ejs文件里把上图“ - 1”给删掉就正常了
![image](https://user-images.githubusercontent.com/35397967/73458776-c4021f80-43b0-11ea-8800-236b38314572.png)

**Comment by yelog** [comment]
已修复

**Comment by zhangyaaoo** [comment]
非常感谢！
