### ISSUE TITLE
it cannot use Google Analytics?

### ISSUE THREAD

**Issue by vikke** [yelog/hexo-theme-3-hexo#65]
I tried to implement google analytics, by reference to http://www.codeblocq.com/2015/12/Add-Google-Analytics-to-your-hexo-blog/

but cannot.

do anyone implements Google Analytics?

**Comment by kaisawind** [comment]
if you want to use google analysisc, the theme must support it.
but 2-hexo don't support google analysis, but it's esay to support it.

add google analysis code to here
hexo-theme-3-hexo/layout/_partial/meta.ejs
https://github.com/kaisawind/hexo-theme-3-hexo/blob/69ca56d635bf8f263c425dca6a716a8db564f5bf/layout/_partial/meta.ejs#L35-L45

add google ua id to
_config.yml
google_analytics: UA-xxxxxxx-xxxx

all  works ok.
https://www.kaisawind.com

**Comment by kaisawind** [comment]
In addition, sometimes gtag  doesn't work.

**Comment by vikke** [comment]
thanks a lot. i'll try it.
