### ISSUE TITLE
How Can I change the order of the posts in the post list?

### ISSUE THREAD

**Issue by alansantosmg** [yelog/hexo-theme-3-hexo#68]
My post list is ascending.  How can I change it to descending order? I tried to set order by in _config.yml global, but I had no effects.  I'm from Brazil, so I hack the code to use DD-MM-YYYY in some files. Can you help me? 
My list on right-panel: 
2017-02-01
2018-01-10
2019-12-20

**Comment by yelog** [comment]
This is hexo's problem, but you can fix this by installing plugin named ` hexo-generator-topindex`

 ```bash
 npm install hexo-generator-topindex --save
```

Besides you can also set top article by parameter `top` as follows
```xml
---
title: This is a artical's title
date: 2017-01-23 11:41:48
top: 1
categories:
- computer
tags:
- git
---
```

**Comment by alansantosmg** [comment]
Ok. I had a error with hexo-generator-topindex, but you gave an idea. 
I tried other package:  hexo-generator-index-updated... yes! It's running. Thank you for your help!
