### ISSUE TITLE
文章目录显示不全

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#7]
文章目录很长时，显示不全，拉滑动条也显示不全。

如：
https://yehuohan.github.io/2017/06/06/%E6%9E%81%E6%96%87/%E5%91%BD%E4%BB%A4%E5%AD%A6%E4%B9%A0-in-Ubuntu/

谢谢！

**Comment by yelog** [comment]
我看了一下，你的文章目录中文章都显示出来了，不过文章不是按照时间排序的，可以参考这篇文章来解决排序问题 ， [Hexo置顶及排序问题](http://yelog.org/2017/02/24/hexo-top-sort/)

**Comment by yehuohan** [comment]
ok, thanks.

**Comment by yelog** [comment]
能帮到你很开心，如果问题解决的话，可以关闭这个issue
