### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by rjd67441** [yelog/hexo-theme-3-hexo#70]
双斜杠  //  后的代码全部被注释 而不是仅仅注释双斜杠以后本行

的内容

而且行号无法关闭

highlight:
  on: true # true开启代码高亮
  lineNum: false # true显示行号
  theme: atom-light

[![1V3Vtx.md.png](https://s2.ax1x.com/2020/01/23/1V3Vtx.md.png)](https://imgchr.com/i/1V3Vtx)

**Comment by lightjiao** [comment]
尝试一下将代码的语言声明一下，以`shell`举例

\```shell
curl https://www.google.com
\```
