### ISSUE TITLE
现在可以渲染数学公式吗？

### ISSUE THREAD

**Issue by yehuohan** [yelog/hexo-theme-3-hexo#8]
现在可以渲染数学公式吗？
貌似没找到渲染公式的字段设置。

**Comment by yelog** [comment]
之前确实加上去，刚才把MathJax加上去了，拉去最新的代码，然后参考[3-hexo配置MathJax数学公式渲染](http://yelog.org/2017/07/05/3-hexo-mathjax/) 进行配置。

**Comment by yehuohan** [comment]
666啊，马上Pull

**Comment by yelog** [comment]
如果使用 `MathJax` 没有问题的话，可以关闭此 `issue`

**Comment by yehuohan** [comment]
可以的，不好意思，现在才收到邮件消息提醒。
谢谢！！

**Comment by yelog** [comment]
哈哈，我也是刚发的消息，你简直就是秒回！

**Comment by yelog** [comment]
刚看了你的站点，文章没有做排序，有点凌乱

**Comment by yehuohan** [comment]
嗯嗯，还没弄排序，我慢慢来吧，功能一点一点加上去。。。。说不定以后还得麻烦你！

**Comment by yelog** [comment]
哈哈
