### ISSUE TITLE
代码无法高亮

### ISSUE THREAD

**Issue by wt-1611** [yelog/hexo-theme-3-hexo#81]
highlight:
  on: true # true开启代码高亮
  lineNum: true # true显示行号
  theme: sunburst
我已经开启代码高亮 
hexo根目录的conf.yml代码高亮也已经关闭了，为什么还是不能高亮呢

**Comment by yelog** [comment]
有效果图，或者效果地址吗

**Comment by wt-1611** [comment]
wtzuishuai.top：4000 ------------------ 原始邮件 ------------------
发件人: "杨玉杰（Chris Yang）"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 上午10:55
收件人: "yelog/hexo-theme-3-hexo"<hexo-theme-3-hexo@noreply.github.com>;
抄送: "wt-1611"<1611058180@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yelog/hexo-theme-3-hexo] 代码无法高亮 (#81)




 
有效果图，或者效果地址吗
 
&mdash;

**Comment by kongzheng1993** [comment]
@wt-1611 兄弟，找到原因了么，我也遇到了，怀疑是不是和之前的主题哪里有冲突的地方。。
@yelog kongzheng1993.github.io  麻烦大佬有时间帮忙看下呗

**Comment by kongzheng1993** [comment]
> @wt-1611 兄弟，找到原因了么，我也遇到了，怀疑是不是和之前的主题哪里有冲突的地方。。
> @yelog kongzheng1993.github.io 麻烦大佬有时间帮忙看下呗



> @wt-1611 兄弟，找到原因了么，我也遇到了，怀疑是不是和之前的主题哪里有冲突的地方。。
> @yelog kongzheng1993.github.io 麻烦大佬有时间帮忙看下呗

关了根目录配置文件的高亮就好了。。。
```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```
