### ISSUE TITLE
gitalk 未登录状态下报错：Error: Bad credentials.

### ISSUE THREAD

**Issue by w4mxl** [yelog/hexo-theme-3-hexo#82]
![image](https://user-images.githubusercontent.com/3645496/77147861-3d70e100-6ac9-11ea-82bf-44dd9e6de4cc.png)

希望得空了能帮忙看下是什么原因，谢谢。
另外我去 [https://github.com/gitalk/gitalk](url) 看到目前最新版本是 1.6.2，
而 3-hexo 主题目前看到的 gitalk 版本是 1.5.0，请问这个需要怎么更新呢？

**Comment by zhu8fei** [comment]
找到 layout/_partial/comments/gitalk.ejs   修改这段:
`$.getScript('<%=theme.blog_path?theme.blog_path.lastIndexOf("/") === theme.blog_path.length-1?theme.blog_path.slice(0, theme.blog_path.length-1):theme.blog_path:'' %>/js/gitalk.js', function () {`
改成:
`$.getScript('https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.js', function () {`

**Comment by w4mxl** [comment]
@zhu8fei 谢谢
