### ISSUE TITLE
自动换行

### ISSUE THREAD

**Issue by ancjf** [yelog/hexo-theme-3-hexo#90]
自动换行要怎么设置？
![image](https://user-images.githubusercontent.com/15904846/79630951-2dabf180-8188-11ea-8f98-cbc415745bc0.png)

**Comment by yelog** [comment]
**代码块**是用来放置代码的，换行不利于阅读代码。

文案等可以考虑使用 **引用块** ，效果如下
>踏莎行·月华如水
>
>清代：纳兰性德
>
>月华如水，波纹似练，几簇淡烟衰柳。塞鸿一夜尽南飞，谁与问倚楼人瘦。
>韵拈风絮，录成金石，不是舞裙歌袖。从前负尽扫眉才，又担阁镜囊重绣。
