### ISSUE TITLE
mobile.style 中 fontsize为空导致了hexo g时报错

### ISSUE THREAD

**Issue by zys980808** [yelog/hexo-theme-3-hexo#91]
https://github.com/yelog/hexo-theme-3-hexo/blob/a03c17f85c8d81dd92952c65ab70416f42746cac/source/css/mobile.styl#L217

报错信息：
```
ERROR Asset render failed: css/mobile.css
CssSyntaxError: ...\thems\3-hexo\source\css\mobile.styl:276:1: Unknown word
```

**Comment by yelog** [comment]
检查一下是否自己修改了 `mobile.styl` ，源码中 `mobile.style` 只有244行
