### ISSUE TITLE
请问如何才能关闭掉快捷键功能呢

### ISSUE THREAD

**Issue by yao-jz** [yelog/hexo-theme-3-hexo#92]
为博客安装了一些插件，与本主题的快捷键冲突，想更改/取消主题的快捷键。
请问该如何操作呢

**Comment by yelog** [comment]
已添加，更新主题后，在 `_config.yml` 内可找到 `shortcutKey`，设为 `false` 即可
```yaml
# 快捷键
shortcutKey: false
```
