### ISSUE TITLE
主题

### ISSUE THREAD

**Issue by guleng** [yelog/hexo-theme-3-hexo#93]
非常感谢主题的开源分享
我看您的站点非常的漂亮，但是我想加几个菜单目录不行，能把最新的主题更新到master分支么？

谢谢

**Comment by yelog** [comment]
master分支就是最新的，目录是在文章头部中声明的，而不是在其他地方

**Comment by guleng** [comment]
还有一个未解决的是怎么才能显示README里的一样显示tags ，我这边显示的是标签图表下一个列表
![image](https://user-images.githubusercontent.com/40238640/83329644-392d2500-a2bd-11ea-83aa-2ad7793a090d.png)

还有就是怎么把All 和About，Friend翻译，我在config里直接更改不行

**Comment by yelog** [comment]
1. 标签已经改版，不支持配置回旧版样式

2. 这个是多语音的问题，需要修改博客下 `_config.yml`
```yml
language: zh-CN #支持 zh-CN、en
```
