### ISSUE TITLE
请问readme里面的tag和 右上角目录怎么没有了

### ISSUE THREAD

**Issue by xiao7462** [yelog/hexo-theme-3-hexo#95]
![](https://tangx-blog.oss-cn-beijing.aliyuncs.com/imags/20200628170819.png)

挺喜欢之前的目录和 tags

**Comment by disheng2018** [comment]
这个不错，我也想要

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
