### ISSUE TITLE
博主能否增强代码的显示？

### ISSUE THREAD

**Issue by xiao7462** [yelog/hexo-theme-3-hexo#96]
类似于这样显示是哪种代码， 有复制功能
![](https://tangx-blog.oss-cn-beijing.aliyuncs.com/imags/20200628193156.png)

并且可以折叠起来
![](https://tangx-blog.oss-cn-beijing.aliyuncs.com/imags/20200628193245.png)
谢谢！

**Comment by yelog** [comment]
代码折叠感觉用处不大，复制代码和类型显示已经添加上去，如下图所示   
或访问 [https://yelog.org/2017/03/23/3-hexo-instruction/](https://yelog.org/2017/03/23/3-hexo-instruction/) 查看效果
![image](https://user-images.githubusercontent.com/14227866/89728096-47d24e00-da5d-11ea-80cf-70f0c577ffdd.png)

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
