### ISSUE TITLE
# 数学公式

### ISSUE THREAD

**Issue by molu-ggg** [yelog/hexo-theme-3-hexo#97]
latex数学公式不能显示

**Comment by molu-ggg** [comment]
已解决，按照网上的操作流程安装一个插件

**Comment by yelog** [comment]
在下面这篇文章中找到 **MathJax 数学公式** 进行调整
[https://yelog.org/2017/03/23/3-hexo-instruction/](https://yelog.org/2017/03/23/3-hexo-instruction/)

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
